name: Build And Publish Keymaps

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v1
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: git clone https://github.com/qmk/qmk_firmware.git
      - name: Install QMK Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc unzip wget zip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          sudo apt-get -y install git python3-pip python3-testresources
      - name: Install QMK
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Remove default crkbd keymaps
        run: rm -rf $HOME/qmk_firmware/keyboards/crkbd/keymaps/*
      - name: Move crkdb keymaps
        run: mv $(pwd)/crkbd/* $HOME/qmk_firmware/keyboards/crkbd/keymaps/
      - name: Compile crkbd keymaps
        run: |
          for dir in $HOME/qmk_firmware/keyboards/crkbd/keymaps/*
          do
            dir=${dir%*/}
            qmk compile -kb crkbd -km $(basename "$dir")
          done
      - name: Move keymaps
        run: mv $HOME/qmk_firmware/*.hex $(pwd)
      - name: Build zip
        run: |
          zip --junk-paths hex-ejemplos.zip *.hex
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hex-ejemplos.zip
          tag: ${{ github.ref }}
          overwrite: true
